package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * ActividadesDTO generated by hbm2java
 */
public class ActividadesDTO implements java.io.Serializable {

	private int codActividades;
	private String descripcion;

	public ActividadesDTO() {
	}

	public ActividadesDTO(int codActividades) {
		this.codActividades = codActividades;
	}

	public ActividadesDTO(int codActividades, String descripcion) {
		this.codActividades = codActividades;
		this.descripcion = descripcion;
	}

	public int getCodActividades() {
		return this.codActividades;
	}

	public void setCodActividades(int codActividades) {
		this.codActividades = codActividades;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
