package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * CuadroComparativoDTO generated by hbm2java
 */
public class CuadroComparativoDTO implements java.io.Serializable {

	private int codCuadroComparativo;
	private ExpedienteCompraDTO expedienteCompraDTO;
	private String url;
	private String fecha;

	public CuadroComparativoDTO() {
	}

	public CuadroComparativoDTO(ExpedienteCompraDTO expedienteCompraDTO) {
		this.expedienteCompraDTO = expedienteCompraDTO;
	}

	public CuadroComparativoDTO(ExpedienteCompraDTO expedienteCompraDTO,
			String url, String fecha) {
		this.expedienteCompraDTO = expedienteCompraDTO;
		this.url = url;
		this.fecha = fecha;
	}

	public int getCodCuadroComparativo() {
		return this.codCuadroComparativo;
	}

	public void setCodCuadroComparativo(int codCuadroComparativo) {
		this.codCuadroComparativo = codCuadroComparativo;
	}

	public ExpedienteCompraDTO getExpedienteCompraDTO() {
		return this.expedienteCompraDTO;
	}

	public void setExpedienteCompraDTO(ExpedienteCompraDTO expedienteCompraDTO) {
		this.expedienteCompraDTO = expedienteCompraDTO;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

}
