package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DetallePacDTO generated by hbm2java
 */
public class DetallePacDTO implements java.io.Serializable {

	private int codDetallePac;
	private String objeto;
	private Double valorRef;
	private String fechaConvocatoria;
	private Set<FormatoRequerimientoDTO> formatoRequerimientoDTOs = new HashSet<FormatoRequerimientoDTO>(
			0);

	public DetallePacDTO() {
	}

	public DetallePacDTO(String objeto, Double valorRef,
			String fechaConvocatoria,
			Set<FormatoRequerimientoDTO> formatoRequerimientoDTOs) {
		this.objeto = objeto;
		this.valorRef = valorRef;
		this.fechaConvocatoria = fechaConvocatoria;
		this.formatoRequerimientoDTOs = formatoRequerimientoDTOs;
	}

	public int getCodDetallePac() {
		return this.codDetallePac;
	}

	public void setCodDetallePac(int codDetallePac) {
		this.codDetallePac = codDetallePac;
	}

	public String getObjeto() {
		return this.objeto;
	}

	public void setObjeto(String objeto) {
		this.objeto = objeto;
	}

	public Double getValorRef() {
		return this.valorRef;
	}

	public void setValorRef(Double valorRef) {
		this.valorRef = valorRef;
	}

	public String getFechaConvocatoria() {
		return this.fechaConvocatoria;
	}

	public void setFechaConvocatoria(String fechaConvocatoria) {
		this.fechaConvocatoria = fechaConvocatoria;
	}

	public Set<FormatoRequerimientoDTO> getFormatoRequerimientoDTOs() {
		return this.formatoRequerimientoDTOs;
	}

	public void setFormatoRequerimientoDTOs(
			Set<FormatoRequerimientoDTO> formatoRequerimientoDTOs) {
		this.formatoRequerimientoDTOs = formatoRequerimientoDTOs;
	}

}
