package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FormatoRequerimientoDTO generated by hbm2java
 */
public class FormatoRequerimientoDTO implements java.io.Serializable {

	private int codFormato;
	private DetallePacDTO detallePacDTO;
	private String fecha;
	private String tipo;
	private String descripcion;
	private Set<RegistroFormatoExpedienteDTO> registroFormatoExpedienteDTOs = new HashSet<RegistroFormatoExpedienteDTO>(
			0);
	private Set<ExpedienteCompraDTO> expedienteCompraDTOs = new HashSet<ExpedienteCompraDTO>(
			0);

	public FormatoRequerimientoDTO() {
	}

	public FormatoRequerimientoDTO(DetallePacDTO detallePacDTO) {
		this.detallePacDTO = detallePacDTO;
	}

	public FormatoRequerimientoDTO(DetallePacDTO detallePacDTO, String fecha,
			String tipo, String descripcion,
			Set<RegistroFormatoExpedienteDTO> registroFormatoExpedienteDTOs,
			Set<ExpedienteCompraDTO> expedienteCompraDTOs) {
		this.detallePacDTO = detallePacDTO;
		this.fecha = fecha;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.registroFormatoExpedienteDTOs = registroFormatoExpedienteDTOs;
		this.expedienteCompraDTOs = expedienteCompraDTOs;
	}

	public int getCodFormato() {
		return this.codFormato;
	}

	public void setCodFormato(int codFormato) {
		this.codFormato = codFormato;
	}

	public DetallePacDTO getDetallePacDTO() {
		return this.detallePacDTO;
	}

	public void setDetallePacDTO(DetallePacDTO detallePacDTO) {
		this.detallePacDTO = detallePacDTO;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<RegistroFormatoExpedienteDTO> getRegistroFormatoExpedienteDTOs() {
		return this.registroFormatoExpedienteDTOs;
	}

	public void setRegistroFormatoExpedienteDTOs(
			Set<RegistroFormatoExpedienteDTO> registroFormatoExpedienteDTOs) {
		this.registroFormatoExpedienteDTOs = registroFormatoExpedienteDTOs;
	}

	public Set<ExpedienteCompraDTO> getExpedienteCompraDTOs() {
		return this.expedienteCompraDTOs;
	}

	public void setExpedienteCompraDTOs(
			Set<ExpedienteCompraDTO> expedienteCompraDTOs) {
		this.expedienteCompraDTOs = expedienteCompraDTOs;
	}

}
