package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * MenuDTO generated by hbm2java
 */
public class MenuDTO implements java.io.Serializable {

	private int codMenu;
	private PerfilDTO perfilDTO;
	private String descripcion;
	private String direccion;

	public MenuDTO() {
	}

	public MenuDTO(PerfilDTO perfilDTO) {
		this.perfilDTO = perfilDTO;
	}

	public MenuDTO(PerfilDTO perfilDTO, String descripcion, String direccion) {
		this.perfilDTO = perfilDTO;
		this.descripcion = descripcion;
		this.direccion = direccion;
	}

	public int getCodMenu() {
		return this.codMenu;
	}

	public void setCodMenu(int codMenu) {
		this.codMenu = codMenu;
	}

	public PerfilDTO getPerfilDTO() {
		return this.perfilDTO;
	}

	public void setPerfilDTO(PerfilDTO perfilDTO) {
		this.perfilDTO = perfilDTO;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
