package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PerfilDTO generated by hbm2java
 */
public class PerfilDTO implements java.io.Serializable {

	private int codPerfil;
	private String descripcion;
	private Set<UsuarioDTO> usuarioDTOs = new HashSet<UsuarioDTO>(0);
	private Set<MenuDTO> menuDTOs = new HashSet<MenuDTO>(0);

	public PerfilDTO() {
	}

	public PerfilDTO(String descripcion, Set<UsuarioDTO> usuarioDTOs,
			Set<MenuDTO> menuDTOs) {
		this.descripcion = descripcion;
		this.usuarioDTOs = usuarioDTOs;
		this.menuDTOs = menuDTOs;
	}

	public int getCodPerfil() {
		return this.codPerfil;
	}

	public void setCodPerfil(int codPerfil) {
		this.codPerfil = codPerfil;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<UsuarioDTO> getUsuarioDTOs() {
		return this.usuarioDTOs;
	}

	public void setUsuarioDTOs(Set<UsuarioDTO> usuarioDTOs) {
		this.usuarioDTOs = usuarioDTOs;
	}

	public Set<MenuDTO> getMenuDTOs() {
		return this.menuDTOs;
	}

	public void setMenuDTOs(Set<MenuDTO> menuDTOs) {
		this.menuDTOs = menuDTOs;
	}

}
