package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * RegistroFormatoExpedienteDTO generated by hbm2java
 */
public class RegistroFormatoExpedienteDTO implements java.io.Serializable {

	private int codRegistroFormatoAndExpediente;
	private ExpedienteCompraDTO expedienteCompraDTO;
	private UsuarioDTO usuarioDTO;
	private FormatoRequerimientoDTO formatoRequerimientoDTO;
	private Integer posicion;
	private String aprobado;
	private String firmado;

	public RegistroFormatoExpedienteDTO() {
	}

	public RegistroFormatoExpedienteDTO(int codRegistroFormatoAndExpediente,
			UsuarioDTO usuarioDTO) {
		this.codRegistroFormatoAndExpediente = codRegistroFormatoAndExpediente;
		this.usuarioDTO = usuarioDTO;
	}

	public RegistroFormatoExpedienteDTO(int codRegistroFormatoAndExpediente,
			ExpedienteCompraDTO expedienteCompraDTO, UsuarioDTO usuarioDTO,
			FormatoRequerimientoDTO formatoRequerimientoDTO, Integer posicion,
			String aprobado, String firmado) {
		this.codRegistroFormatoAndExpediente = codRegistroFormatoAndExpediente;
		this.expedienteCompraDTO = expedienteCompraDTO;
		this.usuarioDTO = usuarioDTO;
		this.formatoRequerimientoDTO = formatoRequerimientoDTO;
		this.posicion = posicion;
		this.aprobado = aprobado;
		this.firmado = firmado;
	}

	public int getCodRegistroFormatoAndExpediente() {
		return this.codRegistroFormatoAndExpediente;
	}

	public void setCodRegistroFormatoAndExpediente(
			int codRegistroFormatoAndExpediente) {
		this.codRegistroFormatoAndExpediente = codRegistroFormatoAndExpediente;
	}

	public ExpedienteCompraDTO getExpedienteCompraDTO() {
		return this.expedienteCompraDTO;
	}

	public void setExpedienteCompraDTO(ExpedienteCompraDTO expedienteCompraDTO) {
		this.expedienteCompraDTO = expedienteCompraDTO;
	}

	public UsuarioDTO getUsuarioDTO() {
		return this.usuarioDTO;
	}

	public void setUsuarioDTO(UsuarioDTO usuarioDTO) {
		this.usuarioDTO = usuarioDTO;
	}

	public FormatoRequerimientoDTO getFormatoRequerimientoDTO() {
		return this.formatoRequerimientoDTO;
	}

	public void setFormatoRequerimientoDTO(
			FormatoRequerimientoDTO formatoRequerimientoDTO) {
		this.formatoRequerimientoDTO = formatoRequerimientoDTO;
	}

	public Integer getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Integer posicion) {
		this.posicion = posicion;
	}

	public String getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(String aprobado) {
		this.aprobado = aprobado;
	}

	public String getFirmado() {
		return this.firmado;
	}

	public void setFirmado(String firmado) {
		this.firmado = firmado;
	}

}
