package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * SaldoPresupuestalDTO generated by hbm2java
 */
public class SaldoPresupuestalDTO implements java.io.Serializable {

	private int codSaldoPresupuestal;
	private String descripcion;
	private Double cantidad;

	public SaldoPresupuestalDTO() {
	}

	public SaldoPresupuestalDTO(String descripcion, Double cantidad) {
		this.descripcion = descripcion;
		this.cantidad = cantidad;
	}

	public int getCodSaldoPresupuestal() {
		return this.codSaldoPresupuestal;
	}

	public void setCodSaldoPresupuestal(int codSaldoPresupuestal) {
		this.codSaldoPresupuestal = codSaldoPresupuestal;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
