package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

/**
 * SolicitudCotizacionHasProveedorDTO generated by hbm2java
 */
public class SolicitudCotizacionHasProveedorDTO implements java.io.Serializable {

	private ProveedorDTO proveedorDTO;
	private SolicitudCotizacionDTO solicitudCotizacionDTO;
	private String elegido;

	public SolicitudCotizacionHasProveedorDTO() {
	}

	public SolicitudCotizacionHasProveedorDTO(ProveedorDTO proveedorDTO,
			SolicitudCotizacionDTO solicitudCotizacionDTO) {
		this.proveedorDTO = proveedorDTO;
		this.solicitudCotizacionDTO = solicitudCotizacionDTO;
	}

	public SolicitudCotizacionHasProveedorDTO( ProveedorDTO proveedorDTO,
			SolicitudCotizacionDTO solicitudCotizacionDTO, String elegido) {
		this.proveedorDTO = proveedorDTO;
		this.solicitudCotizacionDTO = solicitudCotizacionDTO;
		this.elegido = elegido;
	}

	public ProveedorDTO getProveedorDTO() {
		return this.proveedorDTO;
	}

	public void setProveedorDTO(ProveedorDTO proveedorDTO) {
		this.proveedorDTO = proveedorDTO;
	}

	public SolicitudCotizacionDTO getSolicitudCotizacionDTO() {
		return this.solicitudCotizacionDTO;
	}

	public void setSolicitudCotizacionDTO(
			SolicitudCotizacionDTO solicitudCotizacionDTO) {
		this.solicitudCotizacionDTO = solicitudCotizacionDTO;
	}

	public String getElegido() {
		return this.elegido;
	}

	public void setElegido(String elegido) {
		this.elegido = elegido;
	}

}
