package com.java.beans;

// Generated 05-sep-2013 3:08:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudCotizacionDTO generated by hbm2java
 */
public class SolicitudCotizacionDTO implements java.io.Serializable {

	private int codSolicitudCotizacion;
	private ExpedienteCompraDTO expedienteCompraDTO;
	private String url;
	private String fecha;
	private Set<SolicitudCotizacionHasProveedorDTO> solicitudCotizacionHasProveedorDTOs = new HashSet<SolicitudCotizacionHasProveedorDTO>(
			0);

	public SolicitudCotizacionDTO() {
	}

	public SolicitudCotizacionDTO(ExpedienteCompraDTO expedienteCompraDTO) {
		this.expedienteCompraDTO = expedienteCompraDTO;
	}

	public SolicitudCotizacionDTO(
			ExpedienteCompraDTO expedienteCompraDTO,
			String url,
			String fecha,
			Set<SolicitudCotizacionHasProveedorDTO> solicitudCotizacionHasProveedorDTOs) {
		this.expedienteCompraDTO = expedienteCompraDTO;
		this.url = url;
		this.fecha = fecha;
		this.solicitudCotizacionHasProveedorDTOs = solicitudCotizacionHasProveedorDTOs;
	}

	public int getCodSolicitudCotizacion() {
		return this.codSolicitudCotizacion;
	}

	public void setCodSolicitudCotizacion(int codSolicitudCotizacion) {
		this.codSolicitudCotizacion = codSolicitudCotizacion;
	}

	public ExpedienteCompraDTO getExpedienteCompraDTO() {
		return this.expedienteCompraDTO;
	}

	public void setExpedienteCompraDTO(ExpedienteCompraDTO expedienteCompraDTO) {
		this.expedienteCompraDTO = expedienteCompraDTO;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Set<SolicitudCotizacionHasProveedorDTO> getSolicitudCotizacionHasProveedorDTOs() {
		return this.solicitudCotizacionHasProveedorDTOs;
	}

	public void setSolicitudCotizacionHasProveedorDTOs(
			Set<SolicitudCotizacionHasProveedorDTO> solicitudCotizacionHasProveedorDTOs) {
		this.solicitudCotizacionHasProveedorDTOs = solicitudCotizacionHasProveedorDTOs;
	}

}
